### PR TITLE
Add GIF/MP4 support to collection generation

### PR DESCRIPTION
**Pull request by Montspy**
Allows generating collections of animated GIFs/MP4s.
Supports a mix of animated and static images in traits.py

This PR implements #3

PHP TODO:

* [x] thumbnail option (`thumbnails: true/false`)
* [x] thumbnail size (width required, height optional) (`thumbnail_size: [w, h]`)
* [x] animated format (option order: `.gif`, `.webm`, `.mp4`) (`animated_format`)

WIKI TODO:

* [x] strongly suggest animation dimensions are all identical
* [x] briefly explain the differences between the 3 format options
* [x] a note about thumbnails
* [x] a note about audio channels

### CODE REVIEW

**Comment by Montspy** [comment]
Missing from this PR:
Support for MP4
GIF export of MP4 NFTs for the metadata `image` field

**Comment by Montspy** [comment]
Now supports GIF, WebM, MP4 as output
And GIF, WebM and MP4 as layer image input

**Comment by Montspy** [comment]
Thumbnails generation in `generate.py` and support in `metadata.py`
Specify resolution in `traits.py`: `config["thumbnails"]`. If commented out, will not generate thumbnails.
Animated thumbnails are GIF
Static thumbnails are PNG

**Comment by sk33z3r** [comment]
Documenting for later. Container build is failing when trying to install an ffmpeg library, even when forcing some stuff in apt

```
Get:505 http://deb.debian.org/debian bullseye/main amd64 va-driver-all amd64 2.10.0-1 [15.3 kB]
Get:506 http://deb.debian.org/debian bullseye/main amd64 vdpau-driver-all amd64 1.4-3 [8540 B]
Get:507 http://deb.debian.org/debian bullseye/main amd64 x11-utils amd64 7.7+5 [202 kB]
Get:508 http://deb.debian.org/debian bullseye/main amd64 x11-xserver-utils amd64 7.7+8 [168 kB]
Get:509 http://deb.debian.org/debian bullseye/main amd64 xauth amd64 1:1.1-1 [40.5 kB]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/e/expat/libexpat1_2.2.10-2%2bdeb11u2_amd64.deb  404  Not Found [IP: 151.101.130.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/s/systemd/libnss-systemd_247.3-6_amd64.deb  404  Not Found [IP: 199.232.122.132 80]
E: Failed to fetch http://deb.debian.org/debian/pool/main/g/gtk%2b3.0/libgtk-3-common_3.24.24-4_all.deb  404  Not Found [IP: 199.232.122.132 80]
E: Failed to fetch http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl-dev_1.1.1k-1%2bdeb11u1_amd64.deb  404  Not Found [IP: 199.232.122.132 80]
E: Internal Error, No file name for libexpat1:amd64
Fetched 197 MB in 1min 9s (2856 kB/s)
The command '/bin/sh -c apt-get install -y --fix-missing python3 npm ffmpeg' returned a non-zero code: 100
ERROR: Service 'php' failed to build : Build failed
```

_looks_ like the repo just isn't available and returning 404, so maybe it will fix itself at some point today.

**Pull request merged**
